### ISSUE TITLE
NoMethodError: undefined method 'attributes' for an instance of String with Sidekiq < 6.5

### ISSUE THREAD

**Issue by pjar** [silva96/log_bench#72]
Issue found with CC and it generated what comes below:

### Description

log_bench 0.7.0 passes a string to `Sidekiq::CurrentAttributes.persist` in `lib/log_bench/railtie.rb:104`:

```
  Sidekiq::CurrentAttributes.persist("LogBench::Current")
```

  This works on Sidekiq 6.5+ / 7.x where string class names are supported (see [sidekiq#5536](https://github.com/sidekiq/sidekiq/issues/5536)), but on Sidekiq 6.4.x the Save middleware expects an actual class and calls `@klass.attributes` directly, resulting in:

```
  NoMethodError: undefined method 'attributes' for an instance of String
```

  The error is triggered on any model save that fires an async audit (or any Sidekiq client push), since the Save middleware runs on every job enqueue.

#### Steps to reproduce

  1. Use log_bench 0.7.0 with Sidekiq ~> 6.4
  2. Trigger any action that enqueues a Sidekiq job

####  Expected behavior

  The middleware should work regardless of Sidekiq version.

####  Suggested fix

  Either pass the class constant directly:

```
  Sidekiq::CurrentAttributes.persist(LogBench::Current)
```

  Or handle both cases:

```
  klass = defined?(LogBench::Current) ? LogBench::Current : "LogBench::Current"
  Sidekiq::CurrentAttributes.persist(klass)
```

  Or add a Sidekiq version constraint to the gemspec (e.g. >= 6.5).

####  Environment

  - log_bench: 0.7.0
  - sidekiq: 6.4.2
  - rails: 7.0.2.3
  - ruby: 3.4.0

**Comment by silva96** [comment]
@pjar could you please push a PR with the fix? thanks!

I think `Sidekiq::CurrentAttributes.persist(LogBench::Current)` should work, the class should be already defined.
